config/routes.rb
Rails.application.routes.draw do

  resources :videos
  devise_for :users
  resources :rentals, only: [:index, :show, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!
  def index
    # get the rentals that the logged in user has made
    @rentals = Rental.where(user: current_user)
  end

  def show
  end

  def new
    @rental = Rental.new
    @rental.video = Video.find(params[:video_id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title_year_released, :description, :classification, :genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blockbuster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/index.html.erb
<h1>Rentals#index</h1>
<p>Find me in app/views/rentals/index.html.erb</p>

app/views/rentals/new.html.erb
<h1>Rentals#new</h1>
<p>Find me in app/views/rentals/new.html.erb</p>

app/views/rentals/show.html.erb
<h1>Rentals#show</h1>
<p>Find me in app/views/rentals/show.html.erb</p>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title_year_released %>
    <%= form.number_field :title_year_released, id: :video_title_year_released %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :video_description %>
  </div>

  <div class="field">
    <%= form.label :classification %>
    <%= form.text_field :classification, id: :video_classification %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, id: :video_genre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title year released</th>
      <th>Description</th>
      <th>Classification</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title_year_released %></td>
        <td><%= video.description %></td>
        <td><%= video.classification %></td>
        <td><%= video.genre %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Rent', new_rental_path(video_id: video.id) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title year released:</strong>
  <%= @video.title_year_released %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @video.classification %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @video.genre %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>